apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: mpi-word-counter
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - name: mpi-word-counter
            image: pcsg1/mpi-word-counter:2
            command: ["mpirun", "--allow-run-as-root", "-np", "4", "./mpi-word-counter"]
            volumeMounts:
            - name: palavras-volume
              mountPath: /app/palavras.txt
              subPath: palavras.txt
          volumes:
          - name: palavras-volume
            configMap:
              name: palavras-config

    Worker:
      replicas: 3
      template:
        spec:
          containers:
          - name: mpi-word-counter
            image: pcsg1/mpi-word-counter:2
            resources:
              limits:
                cpu: "1"
                memory: "512Mi"